export const drugSeedData = [
  // Cardiologie
  { designation: 'ADRENALINE 01MG/ML INJ', category: 'Cardiologie' },
  { designation: 'AMIODARONE 150MG INJ', category: 'Cardiologie' },
  { designation: 'AMIODARONE 200 MG COMP', category: 'Cardiologie' },
  { designation: 'CAPTOPRIL 25 MG COMP', category: 'Cardiologie' },
  { designation: 'CLIPIDOGREL75 MG COMP', category: 'Cardiologie' },
  { designation: 'DIGOXINE 0,5MG/02ML INJ IV', category: 'Cardiologie' },
  { designation: 'DINITRATE D\'ISOSORBIDE 10 MG INJ', category: 'Cardiologie' },
  { designation: 'DOBUTAMINE 250MG/20ML INJ', category: 'Cardiologie' },
  { designation: 'DOPAMINE 200MG/5ML INJ', category: 'Cardiologie' },
  { designation: 'ESMOLOL 10MG/ML INJ', category: 'Cardiologie' },
  { designation: 'ISOPRENALINE CHL/SULF 0,2 MG INJ', category: 'Cardiologie' },
  { designation: 'LEVOSIMENDAN 12/5MG INJ', category: 'Cardiologie' },
  { designation: 'NICARDIPINE 10MG/10ML INJ IV', category: 'Cardiologie' },
  { designation: 'NORADRENALINE TARTRATE 04 MG/08MG INJ', category: 'Cardiologie' },
  { designation: 'TIROFIBAN INJ 250 µg', category: 'Cardiologie' },
  // Pneumologie
  { designation: 'BUDESONIDE 0,1MG/02ML SUSP INH/NEB', category: 'Pneumologie' },
  { designation: 'BUDESONIDE 0,5MG/2ML SUSP/INH/NEB', category: 'Pneumologie' },
  { designation: 'IPRATRONIUM 0,25 MG', category: 'Pneumologie' },
  { designation: 'IPRATRONIUM 0,5 MG', category: 'Pneumologie' },
  { designation: 'SALBUTAMOL 0,5 INJ', category: 'Pneumologie' },
  { designation: 'SALBUTAMOL 0,5MG/ML INH/NEB AERO', category: 'Pneumologie' },
  { designation: 'SALBUTAMOL SOL NEBUL 05 MG', category: 'Pneumologie' },
  { designation: 'TERBUTALINE INJ', category: 'Pneumologie' },
  { designation: 'TERBUTALINE SULFATE 5MG/2ML SOL P INH', category: 'Pneumologie' },
  // Anesthésie
  { designation: 'ATRACURIUM 50MG/5ML', category: 'Anesthésie' },
  { designation: 'BUPIVACAINE 0,5% 20ML', category: 'Anesthésie' },
  { designation: 'BUPIVACAINE 0,5% 4ML', category: 'Anesthésie' },
  { designation: 'KETAMINE 50 MG/ML INJ', category: 'Anesthésie' },
  { designation: 'LIDOCAINE 01% 10 ML INJ', category: 'Anesthésie' },
  { designation: 'LIDOCAINE 02% 10 ML INJ', category: 'Anesthésie' },
  { designation: 'LIDOCAINE 02% GEL BUCC', category: 'Anesthésie' },
  { designation: 'MEPIVACAINE AVEC VASO ADRENALINE 02%', category: 'Anesthésie' },
  { designation: 'MEPIVACAINE SANS VASO 03%', category: 'Anesthésie' },
  { designation: 'PROPOFOL 200MG/20ML INJ', category: 'Anesthésie' },
  { designation: 'ROCURONIUM BROMURE 50MG/05ML INJ IV', category: 'Anesthésie' },
  { designation: 'SEVOFLURANE LIQ P/INH FL 250 ML', category: 'Anesthésie' },
  { designation: 'SUGAMMADEX 200MG/2ML INJ', category: 'Anesthésie' },
  { designation: 'SUGAMMADEX 500MG/2ML INJ', category: 'Anesthésie' },
  { designation: 'THIOPENTAL SODIQUE 1G INJ', category: 'Anesthésie' },
  { designation: 'THIOPENTAL SODIQUE 500 MG INJ', category: 'Anesthésie' },
  // Hématologie
  { designation: 'ACENOCOUMAROL 04 MG COMP', category: 'Hématologie' },
  { designation: 'ALTEPLASE 50MG/50ML INJ', category: 'Hématologie' },
  { designation: 'FER SACCHAROSE INJ', category: 'Hématologie' },
  { designation: 'HEPARINE CALCIQUE 12500 UI 0,5 ML SC', category: 'Hématologie' },
  { designation: 'HEPARINE SODIQUE 2500 UI 05ML INJ', category: 'Hématologie' },
  { designation: 'TENECTEPLASE 10 000 UI INJ', category: 'Hématologie' },
  // Gastrologie
  { designation: 'ESOMEPRAZOLE INJ', category: 'Gastrologie' },
  { designation: 'METOCLOPRAMIDE 10MG INJ', category: 'Gastrologie' },
  { designation: 'ONDANSETRON 04 MG', category: 'Gastrologie' },
  { designation: 'ONDANSETRON 08 MG', category: 'Gastrologie' },
  { designation: 'PHLORGLUCINOL 10MG/ML INJ', category: 'Gastrologie' },
  // Ophtalmologie
  { designation: 'ATROPINE COLLYRE 0,5%', category: 'Ophtalmologie' },
  { designation: 'ATROPINE COLLYRE 01%', category: 'Ophtalmologie' },
  { designation: 'OXYBUPROCAINE 0,4% COLLYRE', category: 'Ophtalmologie' },
  { designation: 'PHENYLEPHRINE COLLYRE', category: 'Ophtalmologie' },
  { designation: 'TROPICAMID COLLYRE', category: 'Ophtalmologie' },
  // Électrolytes
  { designation: 'CALCIUM CHLORURES 1% 10ML INJ', category: 'Électrolytes' },
  { designation: 'CALCIUM GLUCONATE 10% 10 ML INJ', category: 'Électrolytes' },
  { designation: 'CHLORURES DE POTASSIUM 10% 10 ML INJ', category: 'Électrolytes' },
  { designation: 'CHLORURES DE SODIUM 10% 10ML INJ', category: 'Électrolytes' },
  { designation: 'MAGNESIUM SULFATE 15% 10 ML INJ', category: 'Électrolytes' },
  // Antalgiques / AINS
  { designation: 'ACIDE ACETYLSALYCILIQUE INJ', category: 'Antalgiques / AINS' },
  { designation: 'DICLOFENAC SODIQUE 75 MG INJ', category: 'Antalgiques / AINS' },
  { designation: 'PARACETAMOL AD 10MG/ML 01G', category: 'Antalgiques / AINS' },
  { designation: 'PARACETAMOL ENF/NN 10MG 500MG', category: 'Antalgiques / AINS' },
  // Testes
  { designation: 'BANDELETTES DE GLYCEMIE', category: 'Testes' },
  { designation: 'BANDELETTES DES URINES 05 PARAMETRE', category: 'Testes' },
  { designation: 'BANDELETTES DES URINES 10 PARAMETRE', category: 'Testes' },
  { designation: 'LECTEUR DE GLYCEMIE', category: 'Testes' },
  // Autres
  { designation: 'ACIDE ASCORBIQUE 500 MG INJ', category: 'Autres' },
  { designation: 'ACIDE TRANEXAMIQUE 500MG/05ML INJ', category: 'Autres' },
  { designation: 'ANTIMONIATE DE MEGLUMINE 1,5G/05ML INJ', category: 'Autres' },
  { designation: 'ATROPINE PURE INJ 0,25 MG/ML', category: 'Autres' },
  { designation: 'ATROPINE PURE INJ 01MG/ML', category: 'Autres' },
  { designation: 'BOSENTAN 62,5 MG COMP', category: 'Autres' },
  { designation: 'BOSENTAN 125 MG COMP', category: 'Autres' },
  { designation: 'CARBOXYMALTOSE FERRIQUE INJ', category: 'Autres' },
  { designation: 'CITRATE DE CAFEINE 25MG INJ', category: 'Autres' },
  { designation: 'CLONIDINE 0,15MG INJ', category: 'Autres' },
  { designation: 'CYANOCOBALAMINE 1000 HUG INJ IM', category: 'Autres' },
  { designation: 'DEFERASIROX 250 MG COMP', category: 'Autres' },
  { designation: 'DEFERASIROX 500 MG COMP', category: 'Autres' },
  { designation: 'DEFEROXAMINE 500 MG INJ', category: 'Autres' },
  { designation: 'DEXAMETHASONE 04 MG INJ', category: 'Autres' },
  { designation: 'DEXAMETHASONE 20 MG INJ', category: 'Autres' },
  { designation: 'ETAMSYLATE SODIQUE 250MG/2ML INJ', category: 'Autres' },
  { designation: 'FLUORESCINE 10% AMP 05 ML INJ', category: 'Autres' },
  { designation: 'GLUCOSE 30% 10 ML INJ', category: 'Autres' },
  { designation: 'HUILE DE PARAFFINE FLAC 500 ML', category: 'Autres' },
  { designation: 'HYDROCORTISONE HEMISUCCINATE 100 MG INJ', category: 'Autres' },
  { designation: 'METHYLPREDNISOLONE (20, 40, 120, 500 MG)', category: 'Autres' },
  { designation: 'NALOXONE CHLORHYDRATE INJ', category: 'Autres' },
  { designation: 'POLYSTIRENE SULFATE DE Na', category: 'Autres' },
  { designation: 'PRALIDOXIME 200 MG INJ', category: 'Autres' },
  { designation: 'PREDNISONE BASE 05MG COMP', category: 'Autres' },
  { designation: 'PROMETHASINE 50MG INJ', category: 'Autres' },
  { designation: 'PROPRANOLOL 3,75MG/ML SUSP BUV', category: 'Autres' },
  { designation: 'PROTAMINE SULFATE 1000UAH INJ', category: 'Autres' },
  { designation: 'PYRIDOXINE 250 MG INJ', category: 'Autres' },
  { designation: 'SEL DE REHYDRATATION 20,5 G', category: 'Autres' },
  { designation: 'SULFADIAZINE ARGENTIQUE CREME', category: 'Autres' },
  { designation: 'THIAMINE INJ', category: 'Autres' },
];
