// This configuration is automatically generated by Firebase Studio.
// You should not edit this file manually, as it may be overwritten.
import { z } from 'zod';

const firebaseConfigSchema = z.object({
  apiKey: z.string().min(1, "NEXT_PUBLIC_FIREBASE_API_KEY is not set in .env"),
  authDomain: z.string().min(1, "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN is not set in .env"),
  projectId: z.string().min(1, "NEXT_PUBLIC_FIREBASE_PROJECT_ID is not set in .env"),
  storageBucket: z.string().min(1, "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET is not set in .env"),
  messagingSenderId: z.string().min(1, "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID is not set in .env"),
  appId: z.string().min(1, "NEXT_PUBLIC_FIREBASE_APP_ID is not set in .env"),
});

export const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY!,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN!,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID!,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET!,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID!,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID!,
};

// We only validate the config on the client-side, in the browser.
// This is to avoid server-side warnings about missing env vars during build.
export function isFirebaseConfigValid() {
    if (typeof window === 'undefined') return true;
    const result = firebaseConfigSchema.safeParse(firebaseConfig);
    if (!result.success) {
        console.warn(`Firebase config is not valid. Please set the NEXT_PUBLIC_FIREBASE_* environment variables in your .env file. Errors: ${result.error.flatten().fieldErrors}`);
    }
    return result.success;
}
